### ISSUE TITLE
Server use issue/error

### ISSUE THREAD

**Issue by CypherXero84** [awesomeshot5051/mobFarms#1]
**NeoForge 21.1.77
Minecraft 1.21.1**
_(Personal server)_

Mob Farms works without a hitch in server, but when Plant Farms is used the server returns this error:

**[16:04:37] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
        - Plant Farms (plant_farms) encountered an error while dispatching the net.neoforged.neoforge.registries.RegisterEvent event
          java.lang.RuntimeException: Failed to create item renderer for: chorusFarm**
          
No issues within single player.

**Comment by awesomeshot5051** [comment]
I'll look into it. Can you send me your log file. If you have to send a link to an external drive(google drive, Dropbox, etc.) ensure that anyone who clicks the link has access. Also, ensure you're using the latest version. I've made some updates. It should be the one from the 19th not the 17th.

**Comment by CypherXero84** [comment]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-11-22 16:04:37
Description: Mod loading failures have occurred; consult the issue messages for more details

net.neoforged.neoforge.logging.CrashReportExtender$ModLoadingCrashException: Mod loading has failed


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:60) ~[loader-4.0.31.jar%2360!/:4.0] {}
-- Mod loading issue for: plant_farms --
Details:
	Caused by 0: java.lang.RuntimeException: Failed to create item renderer for: chorusFarm
		at TRANSFORMER/plant_farms@1/com.awesomeshot5051.plantfarms.blocks.BlockBase.createItemWithDynamicRenderer(BlockBase.java:69) ~[plant_farms-1.21.1-1.0.0.jar%23259!/:?] {re:classloading}
		at TRANSFORMER/plant_farms@1/com.awesomeshot5051.plantfarms.blocks.theend.chorusFarmBlock.toItem(chorusFarmBlock.java:47) ~[plant_farms-1.21.1-1.0.0.jar%23259!/:?] {re:classloading,pl:runtimedistcleaner:A}
		at TRANSFORMER/plant_farms@1/com.awesomeshot5051.plantfarms.items.ModItems.lambda$static$1(ModItems.java:20) ~[plant_farms-1.21.1-1.0.0.jar%23259!/:?] {re:classloading}
		at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.DeferredRegister$Items.lambda$register$0(DeferredRegister.java:483) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:classloading}
		at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$1(DeferredRegister.java:234) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:classloading}
		at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.DeferredRegister.lambda$addEntries$2(DeferredRegister.java:375) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:classloading}
		at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.RegisterEvent.register(RegisterEvent.java:48) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:mixin,re:classloading}
		at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.DeferredRegister.addEntries(DeferredRegister.java:375) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:classloading}
		at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2367!/:?] {}
		at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?] {}
		at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:329) ~[bus-8.0.2.jar%2367!/:?] {}
		at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:177) ~[loader-4.0.31.jar%2360!/:4.0] {}
		at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModLoader.lambda$postEventWithWrapInModOrder$16(ModLoader.java:379) ~[loader-4.0.31.jar%2360!/:4.0] {}
		at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
		at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:174) ~[loader-4.0.31.jar%2360!/:4.0] {}
		at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:377) ~[loader-4.0.31.jar%2360!/:4.0] {}
		at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:368) ~[loader-4.0.31.jar%2360!/:4.0] {}
		at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.GameData.postRegisterEvents(GameData.java:92) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:mixin,re:classloading,pl:mixin:APP:supermartijn642corelib.mixins.json:GameDataMixin from mod supermartijn642corelib,pl:mixin:A}
		at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$0(CommonModLoader.java:54) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:classloading}
		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
		at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {}

	Mod file: /C:/Users/Michael Grube/Desktop/FALCOR 21.1.77/mods/plant_farms-1.21.1-1.0.0.jar
	Failure message: Plant Farms (plant_farms) encountered an error while dispatching the net.neoforged.neoforge.registries.RegisterEvent event
		java.lang.RuntimeException: Failed to create item renderer for: chorusFarm
	Mod version: 1
	Mod issues URL: <No issues URL found>
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
Stacktrace:
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:60) ~[loader-4.0.31.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
	at java.base/java.lang.Class.forName(Class.java:421) ~[?:?] {re:mixin}
	at java.base/java.lang.Class.forName(Class.java:412) ~[?:?] {re:mixin}
	at TRANSFORMER/plant_farms@1/com.awesomeshot5051.plantfarms.blocks.BlockBase.createItemWithDynamicRenderer(BlockBase.java:57) ~[plant_farms-1.21.1-1.0.0.jar%23259!/:?] {re:classloading}
	at TRANSFORMER/plant_farms@1/com.awesomeshot5051.plantfarms.blocks.theend.chorusFarmBlock.toItem(chorusFarmBlock.java:47) ~[plant_farms-1.21.1-1.0.0.jar%23259!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/plant_farms@1/com.awesomeshot5051.plantfarms.items.ModItems.lambda$static$1(ModItems.java:20) ~[plant_farms-1.21.1-1.0.0.jar%23259!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.DeferredRegister$Items.lambda$register$0(DeferredRegister.java:483) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$1(DeferredRegister.java:234) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.DeferredRegister.lambda$addEntries$2(DeferredRegister.java:375) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.RegisterEvent.register(RegisterEvent.java:48) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.DeferredRegister.addEntries(DeferredRegister.java:375) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:329) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:177) ~[loader-4.0.31.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModLoader.lambda$postEventWithWrapInModOrder$16(ModLoader.java:379) ~[loader-4.0.31.jar%2360!/:4.0] {}
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:174) ~[loader-4.0.31.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:377) ~[loader-4.0.31.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:368) ~[loader-4.0.31.jar%2360!/:4.0] {}
	at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.registries.GameData.postRegisterEvents(GameData.java:92) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:mixin,re:classloading,pl:mixin:APP:supermartijn642corelib.mixins.json:GameDataMixin from mod supermartijn642corelib,pl:mixin:A}
	at TRANSFORMER/neoforge@21.1.77/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$0(CommonModLoader.java:54) ~[neoforge-21.1.77-universal.jar%23203!/:?] {re:classloading}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.4, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 268772296 bytes (256 MiB) / 1392508928 bytes (1328 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i9-13900K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: Raptor Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 32
	Graphics card #0 name: Intel(R) UHD Graphics 770
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.101.4577
	Graphics card #1 name: NVIDIA GeForce RTX 4090
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 24564.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.6590
	Memory slot #0 capacity (MiB): 32768.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 32768.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 69399.34
	Virtual memory used (MiB): 29048.32
	Swap memory total (MiB): 4096.00
	Swap memory used (MiB): 97.62
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 1060576.25, total: 1907026.63
	Space in storage for workdir (MiB): available: 1060576.25, total: 1907026.63
	JVM Flags: 1 total; -Xmx16G
	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: forgeserver
	ModLauncher services: 
		sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE 
		loader-4.0.31.jar slf4jfixer PLUGINSERVICE 
		loader-4.0.31.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-4.0.31.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		__fabric_loader_bootstrap@2.5.29+0.16.0+1.21
		javafml@4.0
		lowcodefml@4.0
		minecraft@4.0
	Mod List: 
		accessories-neoforge-1.1.0-beta.16+1.21.1.jar     |Accessories                   |accessories                   |1.1.0-beta.16+1.21.1|Manifest: NOSIGNATURE
		additionallanterns-1.1.1-neoforge-mc1.21.jar      |Additional Lanterns           |additionallanterns            |1.1.1               |Manifest: NOSIGNATURE
		architectury-13.0.6-neoforge.jar                  |Architectury                  |architectury                  |13.0.6              |Manifest: NOSIGNATURE
		balm-neoforge-1.21.1-21.0.15.jar                  |Balm                          |balm                          |21.0.15             |Manifest: NOSIGNATURE
		BetterThanMending-neoforge-2.1.0.jar              |BetterThanMending             |betterthanmending             |2.1.0               |Manifest: NOSIGNATURE
		biggerspongeabsorptionradius-1.21.1-3.7.jar       |Bigger Sponge Absorption Radiu|biggerspongeabsorptionradius  |3.7                 |Manifest: NOSIGNATURE
		cloth-config-15.0.128-neoforge.jar                |Cloth Config v15 API          |cloth_config                  |15.0.128            |Manifest: NOSIGNATURE
		collective-1.21.1-7.81.jar                        |Collective                    |collective                    |7.81                |Manifest: NOSIGNATURE
		compatdatapacks76-neoforge-1.0.8.210.jar          |CompatDatapacks               |compatdatapacks76             |1.0.8.210-neoforge  |Manifest: NOSIGNATURE
		ConfigAPI-CJ-neoforge-mc-1.21-2.3.3.jar           |Config API                    |configapi                     |1.20.5-2.2.1        |Manifest: NOSIGNATURE
		corelib-1.21.1-2.1.4.jar                          |Corelib                       |corelib                       |1.21.1-2.1.4        |Manifest: NOSIGNATURE
		bettercrafting-1.21.1-1-neoforge.jar              |Crafting Better               |bettercrafting                |1.21.1-1-neoforge   |Manifest: NOSIGNATURE
		crystal_tools-1.21.1-2.1.6.jar                    |Crystal Tools                 |crystal_tools                 |1.21.1-2.1.6        |Manifest: NOSIGNATURE
		cumulus_menus-1.21.1-1.1.1-neoforge.jar           |Cumulus                       |cumulus_menus                 |1.1.1               |Manifest: NOSIGNATURE
		curios-neoforge-9.0.12+1.21.jar                   |Curios API                    |curios                        |9.0.12+1.21         |Manifest: NOSIGNATURE
		deeperdarker-neoforge-1.21-1.3.0.jar              |Deeper and Darker             |deeperdarker                  |1.3.0               |Manifest: NOSIGNATURE
		disenchanting_table-merged-1.21-3.0.2.jar         |Dis-Enchanting Table          |disenchanting_table           |3.0.2               |Manifest: NOSIGNATURE
		EasySteel-NeoForge-1.21.1-1.9.10.jar              |Easy Steel                    |easy_steel                    |1.9.10              |Manifest: NOSIGNATURE
		elevatorid-1.21-1.10.1.jar                        |Elevator Mod                  |elevatorid                    |1.21-1.10.1         |Manifest: NOSIGNATURE
		end_ore-1.0.0-neoforge-1.21.1.jar                 |End Ore                       |end_ore                       |1.0.0               |Manifest: NOSIGNATURE
		endportalrecipe-1.21.1-5.5.jar                    |End Portal Recipe             |endportalrecipe               |5.5                 |Manifest: NOSIGNATURE
		Enderite-CJ-neoforge-mc-1.21-2.2.4.jar            |Enderite CJ Edition           |enderite                      |1.21-2.2.4          |Manifest: NOSIGNATURE
		everythingcopper-1.21.0-2.3.5.jar                 |Everything is Copper          |everythingcopper              |1.21.0-2.3.5        |Manifest: NOSIGNATURE
		Explorify v1.6.1 f10-48.jar                       |Explorify                     |explorify                     |1.6.1               |Manifest: NOSIGNATURE
		ExtraGems-1.21-(v.3.0.2-NEO).jar                  |Extra Gems                    |extragems                     |3.0.2               |Manifest: NOSIGNATURE
		fabric-api-base-0.4.42+d1308dedd1.jar             |Forgified Fabric API Base     |fabric_api_base               |0.4.42+d1308dedd1   |Manifest: NOSIGNATURE
		fabric-networking-api-v1-4.2.2+a92978fd19.jar     |Forgified Fabric Networking AP|fabric_networking_api_v1      |4.2.2+a92978fd19    |Manifest: NOSIGNATURE
		fabric-screen-api-v1-2.0.24+79a4c2b0d1.jar        |Forgified Fabric Screen API (v|fabric_screen_api_v1          |2.0.24+79a4c2b0d1   |Manifest: NOSIGNATURE
		functionalarmortrim-neoforge-1.21-1.jar           |FunctionalArmorTrim           |functionalarmortrim           |1                   |Manifest: NOSIGNATURE
		geckolib-neoforge-1.21.1-4.6.6.jar                |GeckoLib 4                    |geckolib                      |4.6.6               |Manifest: NOSIGNATURE
		giantspawn-1.21.1-5.2.jar                         |Giant Spawn                   |giantspawn                    |5.2                 |Manifest: NOSIGNATURE
		GildedNetherite-CJ-neoforge-mc-1.21-1.2.2.jar     |Gilded Netherite CJ Edition   |gildednetherite               |1.21-1.2.2          |Manifest: NOSIGNATURE
		healingbed 1.21.1 (neoforge).jar                  |HealingBed                    |healingbed                    |1.21.1              |Manifest: NOSIGNATURE
		heart_crystals-neoforge-1.0.1-1.21.jar            |Heart Crystals                |heart_crystals                |1.0.1-1.21          |Manifest: NOSIGNATURE
		blood-moon-1.1.0.jar                              |Horde Nights                  |mr_blood_moon                 |1.1.0               |Manifest: NOSIGNATURE
		infinitymendingbows-1.jar                         |Infinity Mending              |mr_infinitymendingbows        |1                   |Manifest: NOSIGNATURE
		ironchest-1.21-neoforge-16.0.7.jar                |Iron Chests                   |ironchest                     |1.21-neoforge-16.0.7|Manifest: NOSIGNATURE
		IronBarrels1.21.1-V1.0NeoForge.jar                |IronBarrelsUpdated            |ironbarrels                   |1.0.0               |Manifest: NOSIGNATURE
		jrftl-1.21-neoforge-1.8.0.jar                     |JRFTL                         |jrftl                         |1.8.0               |Manifest: NOSIGNATURE
		ruby-2.6.4.jar                                    |Just another ruby mod!        |ruby                          |2.6.4               |Manifest: NOSIGNATURE
		jei-1.21-neoforge-19.8.2.99.jar                   |Just Enough Items             |jei                           |19.8.2.99           |Manifest: NOSIGNATURE
		kuma-api-neoforge-21.0.4+1.21.jar                 |KumaAPI                       |kuma_api                      |21.0.4              |Manifest: NOSIGNATURE
		lootr-neoforge-1.21-1.10.33.84.jar                |Lootr                         |lootr                         |1.21-1.10.33.84     |Manifest: NOSIGNATURE
		mcw-bridges-3.0.0-mc1.21.1neoforge.jar            |Macaw's Bridges               |mcwbridges                    |3.0.0               |Manifest: NOSIGNATURE
		mcw-doors-1.1.1-mc1.21.1neoforge.jar              |Macaw's Doors                 |mcwdoors                      |1.1.1               |Manifest: NOSIGNATURE
		mcw-fences-1.1.2-mc1.21.1neoforge.jar             |Macaw's Fences and Walls      |mcwfences                     |1.1.2               |Manifest: NOSIGNATURE
		mcw-furniture-3.3.0-mc1.21.1neoforge.jar          |Macaw's Furniture             |mcwfurnitures                 |3.3.0               |Manifest: NOSIGNATURE
		mcw-lights-1.1.1-mc1.21.1neoforge.jar             |Macaw's Lights and Lamps      |mcwlights                     |1.1.1               |Manifest: NOSIGNATURE
		mcw-paths-1.0.5-1.21.1neoforge.jar                |Macaw's Paths and Pavings     |mcwpaths                      |1.0.5               |Manifest: NOSIGNATURE
		mcw-roofs-2.3.1-mc1.21.1neoforge.jar              |Macaw's Roofs                 |mcwroofs                      |2.3.1               |Manifest: NOSIGNATURE
		mcw-trapdoors-1.1.3-mc1.21.1neoforge.jar          |Macaw's Trapdoors             |mcwtrpdoors                   |1.1.3               |Manifest: NOSIGNATURE
		mcw-windows-2.3.0-mc1.21.1neoforge.jar            |Macaw's Windows               |mcwwindows                    |2.3.2               |Manifest: NOSIGNATURE
		many_more_ores_and_crafts-neoforge-1.21.x-1.0.6.ja|Many More Ores and Crafts     |many_more_ores_and_crafts     |1.0.6               |Manifest: NOSIGNATURE
		mcpitanlib-2.3.8-fix.1-1.21-neoforge.jar          |MCPitanLib                    |mcpitanlib                    |2.3.8-fix.1-1.21-neo|Manifest: NOSIGNATURE
		MetalFences-NEOFORGE-1.21.1-1.0.1.jar             |Metal Fences                  |metalfences                   |1.0.1               |Manifest: NOSIGNATURE
		server-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: NOSIGNATURE
		mob_farms-1.21.1-1.0.6.jar                        |Mob Farms                     |mob_farms                     |1                   |Manifest: NOSIGNATURE
		monolib-neoforge-1.21-1.3.0.jar                   |MonoLib                       |monolib                       |1.3.0               |Manifest: NOSIGNATURE
		moreconcrete-neoforge-1.5.2-1.21.1.jar            |More Concrete                 |moreconcrete                  |1.5.2               |Manifest: NOSIGNATURE
		mysticrift_rottenflesh_leather-1.2.3-neoforge-1.21|MysticRift: RottenFlesh Smelt |mysticrift_rottenflesh_leather|1.2.3               |Manifest: NOSIGNATURE
		neoforge-21.1.77-universal.jar                    |NeoForge                      |neoforge                      |21.1.77             |Manifest: NOSIGNATURE
		nitrogen_internals-1.21.1-1.1.22-neoforge.jar     |Nitrogen                      |nitrogen_internals            |1.1.22              |Manifest: NOSIGNATURE
		noisium-neoforge-2.2.1+mc1.21.jar                 |Noisium                       |noisium                       |2.2.1+mc1.21        |Manifest: NOSIGNATURE
		owo-lib-neoforge-0.12.15-beta.9+1.21.jar          |oωo                           |owo                           |0.12.15-beta.9+1.21 |Manifest: NOSIGNATURE
		Patchouli-1.21-87-NEOFORGE.jar                    |Patchouli                     |patchouli                     |1.21-87-NEOFORGE    |Manifest: NOSIGNATURE
		plant_farms-1.21.1-1.0.0.jar                      |Plant Farms                   |plant_farms                   |1                   |Manifest: NOSIGNATURE
		polymorph-neoforge-1.0.6+1.21.1.jar               |Polymorph                     |polymorph                     |1.0.6+1.21.1        |Manifest: NOSIGNATURE
		seals-1.21.0-3.2.3.jar                            |Seals                         |seals                         |3.2.3               |Manifest: NOSIGNATURE
		shulkerboxtooltip-neoforge-5.1.0+1.21.1.jar       |ShulkerBoxTooltip             |shulkerboxtooltip             |5.1.0+1.21.1        |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.17f-neoforge-mc1.21.jar|SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17+f            |Manifest: NOSIGNATURE
		TaxFreeLevels-1.3.13-neoforge-1.20.5.jar          |Tax Free Levels               |taxfreelevels                 |1.3.13              |Manifest: NOSIGNATURE
		aether-1.21.1-1.5.1-beta.2-neoforge.jar           |The Aether                    |aether                        |1.5.1-beta.2        |Manifest: NOSIGNATURE
		twilightforest-1.21.1-4.6.2790-universal.jar      |The Twilight Forest           |twilightforest                |4.6.2790            |Manifest: NOSIGNATURE
		toms-craftable-items-1.1.0.jar                    |Tom's Craftable Items         |mr_toms_craftableitems        |1.1.0               |Manifest: NOSIGNATURE
		toms_storage-1.21-2.0.8.jar                       |Tom's Simple Storage Mod      |toms_storage                  |2.0.8               |Manifest: NOSIGNATURE
		treeharvester-1.21.1-9.0.jar                      |Tree Harvester                |treeharvester                 |9.0                 |Manifest: NOSIGNATURE
		UncraftingTable-neoforge-1.3.8.jar                |Uncrafting Table              |uncraftingtable76             |1.3.8               |Manifest: NOSIGNATURE
		waystones-neoforge-1.21.1-21.1.1.jar              |Waystones                     |waystones                     |21.1.1              |Manifest: NOSIGNATURE
		Xaeros_Minimap_24.4.0_NeoForge_1.21.jar           |Xaero's Minimap               |xaerominimap                  |24.4.0              |Manifest: NOSIGNATURE
		XaerosWorldMap_1.39.0_NeoForge_1.21.jar           |Xaero's World Map             |xaeroworldmap                 |1.39.0              |Manifest: NOSIGNATURE
		XaeroPlus-2.24+neoforge-1.21-WM1.39.0-MM24.4.0.jar|XaeroPlus                     |xaeroplus                     |2.24                |Manifest: NOSIGNATURE
		YungsApi-1.21.1-NeoForge-5.1.1.jar                |YUNG's API                    |yungsapi                      |1.21.1-NeoForge-5.1.|Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.21.1-NeoForge-4.1.0.jar|YUNG's Better Desert Temples  |betterdeserttemples           |1.21.1-NeoForge-4.1.|Manifest: NOSIGNATURE
		YungsBetterDungeons-1.21.1-NeoForge-5.1.0.jar     |YUNG's Better Dungeons        |betterdungeons                |1.21.1-NeoForge-5.1.|Manifest: NOSIGNATURE
		YungsBetterEndIsland-1.21.1-NeoForge-3.1.0.jar    |YUNG's Better End Island      |betterendisland               |1.21.1-NeoForge-3.1.|Manifest: NOSIGNATURE
		YungsBetterJungleTemples-1.21.1-NeoForge-3.1.0.jar|YUNG's Better Jungle Temples  |betterjungletemples           |1.21.1-NeoForge-3.1.|Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.21.1-NeoForge-5.1.0.jar   |YUNG's Better Mineshafts      |bettermineshafts              |1.21.1-NeoForge-5.1.|Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.21.1-NeoForge-3.1.0.|YUNG's Better Nether Fortresse|betterfortresses              |1.21.1-NeoForge-3.1.|Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.21.1-NeoForge-4.1.0.ja|YUNG's Better Ocean Monuments |betteroceanmonuments          |1.21.1-NeoForge-4.1.|Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.21.1-NeoForge-5.1.0.jar  |YUNG's Better Strongholds     |betterstrongholds             |1.21.1-NeoForge-5.1.|Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.21.1-NeoForge-4.1.0.jar    |YUNG's Better Witch Huts      |betterwitchhuts               |1.21.1-NeoForge-4.1.|Manifest: NOSIGNATURE
		YungsBridges-1.21.1-NeoForge-5.1.0.jar            |YUNG's Bridges                |yungsbridges                  |1.21.1-NeoForge-5.1.|Manifest: NOSIGNATURE
		YungsExtras-1.21.1-NeoForge-5.1.0.jar             |YUNG's Extras                 |yungsextras                   |1.21.1-NeoForge-5.1.|Manifest: NOSIGNATURE
	Crash Report UUID: 948577d8-3a25-4bdd-9c5a-d28422996540
	FML: 4.0.31
	NeoForge: 21.1.77

**Comment by awesomeshot5051** [comment]
Also, can you move this issue to the plant farms repository. I know I put the incorrect link in the curseforge. That should be updated.

**Comment by CypherXero84** [comment]
Apologies, multi-tab problems lol I put the issue in the correct repository, with the crash report log

**Comment by awesomeshot5051** [comment]
No problem. Like I said. I put the wrong link in curseforge.
